[build]
  command = ""          # static site; leave blank
  publish = "."         # directory to serve (adjust if you have /dist)

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
